excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Application/Sources/Generated


#Custom
identifier_name:
  min_length: 1
  max_length:
    warning: 40
    error: 50
type_name:
  min_length: 1
  max_length:
    warning: 40
    error: 50
line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
